#!/usr/bin/env python


import sys
from pymongo import MongoClient

from relentlessdrv.datastructures import (
    ADMIN_FIELDS, minimal_schemas
)



client = MongoClient()

dbfields = list(minimal_schemas)

for dbfield in dbfields:

    newdb = client[dbfield]

    for field in minimal_schemas[dbfield]:

        #newdb.create_collection(field)
        newdb[field].insert_one(
            minimal_schemas[dbfield][field]
        )

