#!/usr/bin/env python


#import sys

import copy

# TODO TODO
# MONGODB base SHOULD MOVE TO 
# RELENTLESS-SRV
from relentlessdrv import MongoDB

from relentlessdrv import (
    ADMIN_FIELDS,
    minimal_schema,
    #minimalTemplate,
    templateDocuments,
    docQueries,
)


# set up the database and schema
client = MongoDB()
client.schema = minimal_schema
client.connect()

# block if not empty!
assert not client

# create template with new, unique ids
docs = templateDocuments()
dbquerys = docQueries(docs)

for q in dbquerys:
    client.put(q)

## for 
#client._validate_document(template)
#
#
#
#for db in list(client.schema):
#
#    newdb = client[dbfield]
#
#    for field in list(client.schema[dbfield]):
#
#        newdb.create_collection(field)
#


