#!/usr/bin/env python


import pymongo

from relentlessdrv.datastructures import ADMIN_FIELDS



if __name__ == "__main__":

    db = pymongo.MongoClient()

    dbs = [
        nm for nm in db.list_database_names()
        if nm not in ADMIN_FIELDS
    ]

    for nm in dbs:

        print("\nDatabase: {}".format(type(nm)))
        print("-------------------------")
        print(db[nm].list_collection_names())


    db.close()

