#!/usr/bin/env python


import pymongo


host = "127.0.0.1"
port = 27107


if __name__ == "__main__":

    db = pymongo.MongoClient(
        port=port, host=host,
    )

    print(db.list_collections())

    db.close()

